swagger: "2.0"
info:
  version: 1.0.0
  title: VolunteeroSearchService
  description: Search service for volunteero entities
basePath: /api/v1

consumes:
  - application/json
produces:
  - application/json

paths:  
  /search:
    get:
      description: Search API for volunteero
      responses:
        200:
          description: Successful search result

